[package]
name = "vs-register"
description = "Image registration, alignment and robust stacking for VapourSynth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vsip-core.workspace = true
vsip-plugin-api.workspace = true

[lints]
workspace = true
