[package]
name = "vs-flowfield"
description = "Dense motion fields, confidence and warping for VapourSynth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
vsip-plugin-api.workspace = true

[lints]
workspace = true
